server:
  port: 9090
spring:
  application:
    name: mirco-system
  thymeleaf:
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://eureka:20000/eureka
ribbon:
  ReadTimeout: 5000