server:
  port: 8085
spring:
  application:
    name: mirco-search
  elasticsearch:
    rest:
      uris: http://localhost:9200
  rabbitmq:
    host: 192.168.148.133
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual # 消息手动确认
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
